"""tr_file_status change default value

Revision ID: 0bdb913aa547
Revises: 9768f2b4b916
Create Date: 2022-11-30 14:34:53.783701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bdb913aa547'
down_revision = '9768f2b4b916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transport_file', 'tr_file_status', server_default="pending")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transport_file', 'tr_file_status', server_default="Pending")
    # ### end Alembic commands ###
