"""changing date and time format to string

Revision ID: 17f09ba47cc8
Revises: 4b160bd59f40
Create Date: 2022-11-10 09:59:56.598332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f09ba47cc8'
down_revision = '4b160bd59f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='activity', column_name='time_1', type_=sa.VARCHAR())
    op.alter_column(table_name='activity', column_name='time_2', type_=sa.VARCHAR())
    op.alter_column(table_name='activity', column_name='date', type_=sa.VARCHAR())
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='activity', column_name='time_1', existing_type=sa.Time)
    op.alter_column(table_name='activity', column_name='time_2', existing_type=sa.Time)
    op.alter_column(table_name='activity', column_name='date', existing_type=sa.Date)    # ### end Alembic commands ###
