"""clean

Revision ID: 1f3f2f66947e
Revises: 
Create Date: 2023-01-31 02:36:37.344223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3f2f66947e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tr_file_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tr_file_id'], ['transport_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transport_file', sa.Column('reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transport_file', 'reference')
    op.drop_table('attachment')
    # ### end Alembic commands ###
