"""generate_initial_schemas

Revision ID: 27b92a99e3e5
Revises: 
Create Date: 2022-04-12 14:29:11.123505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27b92a99e3e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	
	op.create_table(
		'goods',
		sa.Column('id', sa.Integer, autoincrement=True, nullable=False),
		sa.Column('unit_type', sa.String, autoincrement=False, nullable=False),
		sa.Column('stackable', sa.Boolean, autoincrement=False, nullable=False),
		sa.Column('quantity', sa.Integer, autoincrement=False, nullable=False),
		sa.Column('description', sa.String, autoincrement=False, nullable=False),
		sa.Column('loading_meters', sa.Float, autoincrement=False, nullable=False),
		sa.Column('net_weight', sa.Float, autoincrement=False, nullable=True),
		sa.Column('gross_weight', sa.Float, autoincrement=False, nullable=False),
		sa.Column('dangerous_goods', sa.Boolean, autoincrement=False, nullable=False),
		sa.Column('dg_class', sa.String, autoincrement=False, nullable=True),
		sa.Column('dg_product_group', sa.String, autoincrement=False, nullable=True),
		sa.Column('dg_un_code', sa.String, autoincrement=False, nullable=True),
		sa.Column('dg_technical_name', sa.String, autoincrement=False, nullable=True),
		sa.PrimaryKeyConstraint('id')
	)
	op.create_table(
		'address',
		sa.Column('id', sa.Integer, autoincrement=True, nullable=False),
		sa.Column('name', sa.String, autoincrement=False, nullable=False),
		sa.Column('street_1', sa.String, autoincrement=False, nullable=False),
		sa.Column('street_2', sa.String, autoincrement=False, nullable=True),
		sa.Column('street_3', sa.String, autoincrement=False, nullable=True),
		sa.Column('zipcode', sa.String, autoincrement=False, nullable=False),
		sa.Column('country', sa.String, autoincrement=False, nullable=False),
		sa.Column('latitude', sa.Float, autoincrement=False, nullable=False),
		sa.Column('longitude', sa.Float, autoincrement=False, nullable=False),
		sa.PrimaryKeyConstraint('id')
	)
	op.create_table(
		'activity',
		sa.Column('activity_reference', sa.Integer, autoincrement=True, nullable=False),
		sa.Column('id_sequence', sa.Integer, autoincrement=False, nullable=False),
		sa.Column('address_id', sa.Integer,autoincrement=False, nullable=True),
		sa.Column('date', sa.Date, autoincrement=False, nullable=False),
		sa.Column('time_prefix', sa.String, autoincrement=False, nullable=False),
		sa.Column('time_1', postgresql.TIME, autoincrement=False, nullable=False),
		sa.Column('time_2', postgresql.TIME, autoincrement=False, nullable=True),
		sa.Column('goods_id', sa.Integer, sa.ForeignKey("goods.id"), autoincrement=False, nullable=True),
		sa.ForeignKeyConstraint(
			['goods_id'],
			['goods.id'],
			ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(
			['address_id'],
			['address.id'],
			ondelete="CASCADE")
		,
		sa.PrimaryKeyConstraint('activity_reference')
	)
	op.create_table(
		'transport_file',
		sa.Column('id', sa.Integer, autoincrement=True, nullable=False),
		sa.Column('display_number', sa.String, autoincrement=False, nullable=False),
		sa.Column('client', sa.String, autoincrement=False, nullable=False),
		sa.Column('contact', sa.String, autoincrement=False, nullable=False),
		sa.Column('invoice_reference', sa.String, autoincrement=False, nullable=True),
		sa.Column('file_type', sa.String, autoincrement=False, nullable=True),
		sa.Column('equipment_type', sa.String, autoincrement=False, nullable=True),
		sa.Column('modality', sa.String, autoincrement=False, nullable=True),
		sa.Column('service_level', sa.String, autoincrement=False, nullable=True),
		sa.Column('customs', sa.String, autoincrement=False, nullable=True),
		sa.Column('attention_required', sa.Boolean, autoincrement=False, nullable=True),
		sa.Column('department', sa.String, autoincrement=False, nullable=True),
		sa.Column('employee', sa.String, autoincrement=False, nullable=True),
		sa.Column('cost_code', sa.String, autoincrement=False, nullable=True),
		sa.Column('activity_reference', sa.Integer, autoincrement=False, nullable=True),
		sa.ForeignKeyConstraint(
			['activity_reference'],
			['activity.activity_reference'],
			ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint('id')
	)

# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('transport_file')
	op.drop_table('address')
	op.drop_table('goods')
	op.drop_table('activity')
# ### end Alembic commands ###
