"""changing fields in goods

Revision ID: 299cfbd6c045
Revises: 0734f65d6637
Create Date: 2022-12-08 20:01:58.200742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '299cfbd6c045'
down_revision = '0734f65d6637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='goods', column_name='loading_meters', type_=sa.String())
    op.alter_column(table_name='goods', column_name='net_weight', type_=sa.String())
    op.alter_column(table_name='goods', column_name='gross_weight', type_=sa.String())
    op.add_column(table_name='goods', column=sa.Column('width', sa.String(), nullable=True, ))
    op.add_column(table_name='goods', column=sa.Column('height', sa.String(), nullable=True))
    op.add_column(table_name='goods', column=sa.Column('length', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name='goods', column_name='width')
    op.drop_column(table_name='goods', column_name='height')
    op.drop_column(table_name='goods', column_name='length')
    # ### end Alembic commands ###
