"""clean

Revision ID: 343880505faf
Revises: 
Create Date: 2023-01-31 01:43:24.385533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343880505faf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
