"""Changing_child_objects_of_transport_file

Revision ID: 411bb25040c2
Revises: 67f97ac60733
Create Date: 2022-04-25 17:34:14.150081

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '411bb25040c2'
down_revision = '67f97ac60733'
branch_labels = None
depends_on = None


def upgrade():
	
	print("Changing child object of transport_file to have many to one relationships")
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint('client_transport_file_id_fkey', 'client', type_='foreignkey')
	op.drop_column('client', 'transport_file_id')
	
	op.drop_constraint('contact_transport_file_id_fkey', 'contact', type_='foreignkey')
	op.drop_column('contact', 'transport_file_id')
	
	op.drop_constraint('department_transport_file_id_fkey', 'department', type_='foreignkey')
	op.drop_column('department', 'transport_file_id')
	
	op.drop_constraint('employee_transport_file_id_fkey', 'employee', type_='foreignkey')
	op.drop_column('employee', 'transport_file_id')
	
	op.add_column('transport_file', sa.Column('client_id', sa.Integer(), nullable=True))
	op.add_column('transport_file', sa.Column('contact_id', sa.Integer(), nullable=True))
	op.add_column('transport_file', sa.Column('department_id', sa.Integer(), nullable=True))
	op.add_column('transport_file', sa.Column('employee_id', sa.Integer(), nullable=True))
	
	op.create_foreign_key("client_tr_file_fkey", 'transport_file', 'client', ['client_id'], ['id'])
	op.create_foreign_key("department_tr_file_fkey", 'transport_file', 'department', ['department_id'], ['id'])
	op.create_foreign_key("employee_tr_file_fkey", 'transport_file', 'employee', ['employee_id'], ['id'])
	op.create_foreign_key("contact_tr_file_fkey", 'transport_file', 'contact', ['contact_id'], ['id'])


# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint("client_tr_file_fkey", 'transport_file', type_='foreignkey')
	op.drop_constraint("department_tr_file_fkey", 'transport_file', type_='foreignkey')
	op.drop_constraint("employee_tr_file_fkey", 'transport_file', type_='foreignkey')
	op.drop_constraint("contact_tr_file_fkey", 'transport_file', type_='foreignkey')
	
	op.drop_column('transport_file', 'employee_id')
	op.drop_column('transport_file', 'department_id')
	op.drop_column('transport_file', 'contact_id')
	op.drop_column('transport_file', 'client_id')
	
	op.add_column('employee', sa.Column('transport_file_id', sa.INTEGER(), autoincrement=False, nullable=False))
	op.create_foreign_key(
		'employee_tr_file_id_fkey', 'employee', 'transport_file', ['transport_file_id'], ['id'],
		ondelete='CASCADE')
	
	op.add_column('department', sa.Column('transport_file_id', sa.INTEGER(), autoincrement=False, nullable=False))
	op.create_foreign_key(
		'department_tr_file_id_fkey', 'department', 'transport_file', ['transport_file_id'], ['id'],
		ondelete='CASCADE')
	
	op.add_column('contact', sa.Column('transport_file_id', sa.INTEGER(), autoincrement=False, nullable=False))
	op.create_foreign_key(
		'contact_tr_file_id_fkey', 'contact', 'transport_file', ['transport_file_id'], ['id'],
		ondelete='CASCADE')
	
	op.add_column('client', sa.Column('transport_file_id', sa.INTEGER(), autoincrement=False, nullable=False))
	op.create_foreign_key(
		'client_tr_file_id_fkey', 'client', 'transport_file', ['transport_file_id'], ['id'],
		ondelete='CASCADE')

# ### end Alembic commands ###
