"""Added city row in address

Revision ID: 4b160bd59f40
Revises: 19a19ac18a6c
Create Date: 2022-08-23 10:37:14.439143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b160bd59f40'
down_revision = '19a19ac18a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('city', sa.String(), server_default=sa.text("'Example_city'"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'city')
    # ### end Alembic commands ###
