"""added

Revision ID: 733005d18d9b
Revises: c3db50fc9db7
Create Date: 2023-01-31 12:03:56.372664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733005d18d9b'
down_revision = 'c3db50fc9db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
