"""removed

Revision ID: 7aaf378d19b4
Revises: 1f3f2f66947e
Create Date: 2023-01-31 02:43:54.704693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aaf378d19b4'
down_revision = '1f3f2f66947e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
