"""adding created_at column

Revision ID: 81379cc0ab5e
Revises: 411bb25040c2
Create Date: 2022-05-10 13:25:02.981251

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '81379cc0ab5e'
down_revision = '411bb25040c2'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		'activity',
		sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False)
	)
	op.add_column(
		'address',
		sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False)
	)
	op.add_column(
		'client',
		sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False)
	)
	op.add_column(
		'contact',
		sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False)
	)
	op.add_column(
		'department',
		sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False)
	)
	op.add_column(
		'employee',
		sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False)
	)
	op.add_column(
		'goods',
		sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False)
	)
	op.add_column(
		'transport_file',
		sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False)
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('transport_file', 'created_at')
	op.drop_column('goods', 'created_at')
	op.drop_column('employee', 'created_at')
	op.drop_column('department', 'created_at')
	op.drop_column('contact', 'created_at')
	op.drop_column('client', 'created_at')
	op.drop_column('address', 'created_at')
	op.drop_column('activity', 'created_at')
	# ### end Alembic commands ###
