"""adding image ref field

Revision ID: 9768f2b4b916
Revises: 17f09ba47cc8
Create Date: 2022-11-30 13:51:14.139016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9768f2b4b916'
down_revision = '17f09ba47cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport_file', sa.Column('tr_file_image_ref', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transport_file', 'tr_file_image_ref')
    # ### end Alembic commands ###
