"""tr_file_status added

Revision ID: 9b28a1c8dc26
Revises: efad19600d44
Create Date: 2022-05-24 11:19:43.277699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b28a1c8dc26'
down_revision = 'efad19600d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'transport_file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activity', 'instructions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('activity_address_id_fkey', 'activity', type_='foreignkey')
    op.drop_constraint('fk_activity_transport_file', 'activity', type_='foreignkey')
    op.create_foreign_key(
       "fk_activity_address_id", 'activity', 'address', ['address_id'], ['id'])
    op.create_foreign_key(
       "fk_activity_transport_file_id", 'activity', 'transport_file', ['transport_file_id'], ['id'])
    op.alter_column('goods', 'activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('fk_goods_activity', 'goods', type_='foreignkey')
    op.create_foreign_key("fk_goods_activity_id", 'goods', 'activity', ['activity_id'], ['activity_reference'])
    op.add_column('transport_file', sa.Column('tr_file_status', sa.String(), server_default='Pending', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transport_file', 'tr_file_status')
    op.drop_constraint("fk_goods_activity_id", 'goods', type_='foreignkey')
    op.create_foreign_key('fk_goods_activity', 'goods', 'activity', ['activity_id'], ['activity_reference'], ondelete='CASCADE')
    op.alter_column('goods', 'activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint("fk_activity_address_id", 'activity', type_='foreignkey')
    op.drop_constraint("fk_activity_transport_file_id", 'activity', type_='foreignkey')
    op.create_foreign_key('fk_activity_transport_file', 'activity', 'transport_file', ['transport_file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('activity_address_id_fkey', 'activity', 'address', ['address_id'], ['id'], ondelete='CASCADE')
    op.alter_column('activity', 'instructions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('activity', 'transport_file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
