"""changing goods.quantity to string

Revision ID: c1736b054d82
Revises: 299cfbd6c045
Create Date: 2022-12-12 12:04:12.123724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1736b054d82'
down_revision = '299cfbd6c045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name="goods", column_name="quantity", type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name="goods", column_name="quantity", type_=sa.Integer())
    # ### end Alembic commands ###
