"""added

Revision ID: dc14ed12abd4
Revises: 7aaf378d19b4
Create Date: 2023-01-31 11:55:39.358790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc14ed12abd4'
down_revision = '7aaf378d19b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
