"""adding activity_type

Revision ID: efad19600d44
Revises: 81379cc0ab5e
Create Date: 2022-05-17 11:56:55.152631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efad19600d44'
down_revision = '81379cc0ab5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('activity_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'activity_type')
    # ### end Alembic commands ###
